FROM busybox

LABEL maintainer="luismi"

WORKDIR /app
ADD https://raw.githubusercontent.com/lmlopezmagana/git-exam-ubeda-interesa/main/index.html .
ENTRYPOINT ["cat","index.html"]
# https://raw.githubusercontent.com/lmlopezmagana/git-exam-ubeda-interesa/main/index.html
